### ISSUE TITLE
first_segment argument seems strangely used

### ISSUE THREAD

**Issue by myst6re** [AleksanteriHirvonen/wmx2obj#1]
In `convert_to_obj`, the function `convert_segment` is called with the argument `i - cfg->first_segment`. Since `i` start from `cfg->first_segment`, this means that no matter the value of `cfg->first_segment`, `convert_segment` will always be called from 0 to `(cfg->last_segment - cfg->first_segment)`.

**Comment by cospi** [comment]
This is done to guarantee that the converted 3D model will start from position (0, 0, 0). Hence, the parameter name `seg_pos_idx` instead of `seg_idx`. The seeking to the correct first segment in the input file is done before the conversion in `alloc_config`.

This might cause a bug where segments in the converted 3D model end up on the wrong rows, though. I will take a look at it.
